/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Products } from "./Products";
import { ProductsCountArgs } from "./ProductsCountArgs";
import { ProductsFindManyArgs } from "./ProductsFindManyArgs";
import { ProductsFindUniqueArgs } from "./ProductsFindUniqueArgs";
import { DeleteProductsArgs } from "./DeleteProductsArgs";
import { ProductsService } from "../products.service";
@graphql.Resolver(() => Products)
export class ProductsResolverBase {
  constructor(protected readonly service: ProductsService) {}

  async _productsItemsMeta(
    @graphql.Args() args: ProductsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Products])
  async productsItems(
    @graphql.Args() args: ProductsFindManyArgs
  ): Promise<Products[]> {
    return this.service.productsItems(args);
  }

  @graphql.Query(() => Products, { nullable: true })
  async products(
    @graphql.Args() args: ProductsFindUniqueArgs
  ): Promise<Products | null> {
    const result = await this.service.products(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Products)
  async deleteProducts(
    @graphql.Args() args: DeleteProductsArgs
  ): Promise<Products | null> {
    try {
      return await this.service.deleteProducts(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
