/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrderItems } from "./OrderItems";
import { OrderItemsCountArgs } from "./OrderItemsCountArgs";
import { OrderItemsFindManyArgs } from "./OrderItemsFindManyArgs";
import { OrderItemsFindUniqueArgs } from "./OrderItemsFindUniqueArgs";
import { DeleteOrderItemsArgs } from "./DeleteOrderItemsArgs";
import { OrderItemsService } from "../orderItems.service";
@graphql.Resolver(() => OrderItems)
export class OrderItemsResolverBase {
  constructor(protected readonly service: OrderItemsService) {}

  async _orderItemsItemsMeta(
    @graphql.Args() args: OrderItemsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrderItems])
  async orderItemsItems(
    @graphql.Args() args: OrderItemsFindManyArgs
  ): Promise<OrderItems[]> {
    return this.service.orderItemsItems(args);
  }

  @graphql.Query(() => OrderItems, { nullable: true })
  async orderItems(
    @graphql.Args() args: OrderItemsFindUniqueArgs
  ): Promise<OrderItems | null> {
    const result = await this.service.orderItems(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrderItems)
  async deleteOrderItems(
    @graphql.Args() args: DeleteOrderItemsArgs
  ): Promise<OrderItems | null> {
    try {
      return await this.service.deleteOrderItems(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
