/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CustomizablePcPieces as PrismaCustomizablePcPieces,
} from "@prisma/client";

export class CustomizablePcPiecesServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CustomizablePcPiecesCountArgs, "select">
  ): Promise<number> {
    return this.prisma.customizablePcPieces.count(args);
  }

  async customizablePcPiecesItems<
    T extends Prisma.CustomizablePcPiecesFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CustomizablePcPiecesFindManyArgs>
  ): Promise<PrismaCustomizablePcPieces[]> {
    return this.prisma.customizablePcPieces.findMany<Prisma.CustomizablePcPiecesFindManyArgs>(
      args
    );
  }
  async customizablePcPieces<
    T extends Prisma.CustomizablePcPiecesFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CustomizablePcPiecesFindUniqueArgs>
  ): Promise<PrismaCustomizablePcPieces | null> {
    return this.prisma.customizablePcPieces.findUnique(args);
  }
  async createCustomizablePcPieces<
    T extends Prisma.CustomizablePcPiecesCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CustomizablePcPiecesCreateArgs>
  ): Promise<PrismaCustomizablePcPieces> {
    return this.prisma.customizablePcPieces.create<T>(args);
  }
  async updateCustomizablePcPieces<
    T extends Prisma.CustomizablePcPiecesUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CustomizablePcPiecesUpdateArgs>
  ): Promise<PrismaCustomizablePcPieces> {
    return this.prisma.customizablePcPieces.update<T>(args);
  }
  async deleteCustomizablePcPieces<
    T extends Prisma.CustomizablePcPiecesDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.CustomizablePcPiecesDeleteArgs>
  ): Promise<PrismaCustomizablePcPieces> {
    return this.prisma.customizablePcPieces.delete(args);
  }
}
