/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CustomizablePcPieces } from "./CustomizablePcPieces";
import { CustomizablePcPiecesCountArgs } from "./CustomizablePcPiecesCountArgs";
import { CustomizablePcPiecesFindManyArgs } from "./CustomizablePcPiecesFindManyArgs";
import { CustomizablePcPiecesFindUniqueArgs } from "./CustomizablePcPiecesFindUniqueArgs";
import { DeleteCustomizablePcPiecesArgs } from "./DeleteCustomizablePcPiecesArgs";
import { CustomizablePcPiecesService } from "../customizablePcPieces.service";
@graphql.Resolver(() => CustomizablePcPieces)
export class CustomizablePcPiecesResolverBase {
  constructor(protected readonly service: CustomizablePcPiecesService) {}

  async _customizablePcPiecesItemsMeta(
    @graphql.Args() args: CustomizablePcPiecesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CustomizablePcPieces])
  async customizablePcPiecesItems(
    @graphql.Args() args: CustomizablePcPiecesFindManyArgs
  ): Promise<CustomizablePcPieces[]> {
    return this.service.customizablePcPiecesItems(args);
  }

  @graphql.Query(() => CustomizablePcPieces, { nullable: true })
  async customizablePcPieces(
    @graphql.Args() args: CustomizablePcPiecesFindUniqueArgs
  ): Promise<CustomizablePcPieces | null> {
    const result = await this.service.customizablePcPieces(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CustomizablePcPieces)
  async deleteCustomizablePcPieces(
    @graphql.Args() args: DeleteCustomizablePcPiecesArgs
  ): Promise<CustomizablePcPieces | null> {
    try {
      return await this.service.deleteCustomizablePcPieces(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
