/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CartItems } from "./CartItems";
import { CartItemsCountArgs } from "./CartItemsCountArgs";
import { CartItemsFindManyArgs } from "./CartItemsFindManyArgs";
import { CartItemsFindUniqueArgs } from "./CartItemsFindUniqueArgs";
import { DeleteCartItemsArgs } from "./DeleteCartItemsArgs";
import { CartItemsService } from "../cartItems.service";
@graphql.Resolver(() => CartItems)
export class CartItemsResolverBase {
  constructor(protected readonly service: CartItemsService) {}

  async _cartItemsItemsMeta(
    @graphql.Args() args: CartItemsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CartItems])
  async cartItemsItems(
    @graphql.Args() args: CartItemsFindManyArgs
  ): Promise<CartItems[]> {
    return this.service.cartItemsItems(args);
  }

  @graphql.Query(() => CartItems, { nullable: true })
  async cartItems(
    @graphql.Args() args: CartItemsFindUniqueArgs
  ): Promise<CartItems | null> {
    const result = await this.service.cartItems(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CartItems)
  async deleteCartItems(
    @graphql.Args() args: DeleteCartItemsArgs
  ): Promise<CartItems | null> {
    try {
      return await this.service.deleteCartItems(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
